package com.ejada.practice.entity;

import jakarta.persistence.*;
import lombok.*;

import java.util.HashSet;
import java.util.Set;

/**
 * JPA entity representing a product category.
 *
 * <p>Categories are used to group related {@link Product}s together.
 * The relationship between {@code Category} and {@code Product} is
 * many-to-many and is owned by the {@code Product} side via the
 * {@code product_category} join table.</p>
 *
 * <p>Mapped to the {@code categories} database table.</p>
 */
@Entity
@Table(name = "categories")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Category {

    /**
     * Surrogate primary key, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique, human-readable name of the category (e.g. "Electronics").
     * Must not be {@code null}.
     */
    @Column(nullable = false, unique = true)
    private String name;

    /**
     * The set of products that belong to this category.
     * Mapped by the {@code categories} field on the {@link Product} side.
     */
    @ManyToMany(mappedBy = "categories")
    @Builder.Default
    private Set<Product> products;
}
