package com.ejada.practice.entity;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;

/**
 * JPA entity representing a single line item within an {@link Order}.
 *
 * <p>Each {@code OrderItem} captures the product ordered, the quantity,
 * and the unit price at the time of purchase so that historical order
 * values remain accurate even if the product's current price changes later.</p>
 *
 * <p>Mapped to the {@code order_items} database table.</p>
 */
@Entity
@Table(name = "order_items")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class OrderItem {

    /**
     * Surrogate primary key, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The parent order this line item belongs to.
     * Loaded lazily; the association is mandatory (an item cannot exist without an order).
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "order_id", nullable = false)
    private Order order;

    /**
     * The product that was ordered.
     * Loaded lazily; the association is mandatory.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    /**
     * Number of units of the product included in this line item.
     * Must be at least 1.
     */
    @Column(nullable = false)
    private Integer quantity;

    /**
     * Unit price of the product at the moment the order was placed.
     * Stored with 12 integer digits and 2 decimal places to preserve monetary precision.
     */
    @Column(name = "price_at_purchase", nullable = false, precision = 12, scale = 2)
    private BigDecimal priceAtPurchase;
}
