package com.ejada.practice.entity;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

/**
 * JPA entity representing a customer order.
 *
 * <p>An order is placed by a {@link User} and contains one or more
 * {@link OrderItem}s.  The order lifecycle is tracked via an
 * {@link OrderStatus} enum (e.g. {@code PENDING → CONFIRMED → SHIPPED → DELIVERED}).</p>
 *
 * <p>Mapped to the {@code orders} database table.</p>
 */
@Entity
@Table(name = "orders")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Order {

    /**
     * Surrogate primary key, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The customer who placed this order.
     * Loaded lazily to avoid unnecessary joins on every fetch.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Timestamp at which the order was submitted.
     * Set to {@link LocalDateTime#now()} at creation and never changed.
     */
    @Column(name = "order_date", nullable = false)
    private LocalDateTime orderDate;

    /**
     * Current lifecycle status of the order.
     * Stored as its string name (e.g. {@code "PENDING"}) in the database.
     *
     * @see OrderStatus
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private OrderStatus status;

    /**
     * Pre-calculated sum of all line totals for this order.
     * Stored with 12 integer digits and 2 decimal places (e.g. USD cents precision).
     */
    @Column(name = "total_amount", nullable = false, precision = 12, scale = 2)
    private BigDecimal totalAmount;

    /**
     * The individual line items contained in this order.
     * Cascade type {@code ALL} ensures items are persisted / deleted with the order.
     */
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<OrderItem> items;
}
