package com.ejada.practice.entity;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * JPA entity representing a product available in the catalogue.
 *
 * <p>A product belongs to zero or more {@link Category}s via a many-to-many
 * relationship stored in the {@code product_category} join table.
 * Stock is tracked via {@link #stockQuantity}, which is decremented when
 * an order is placed.</p>
 *
 * <p>Mapped to the {@code products} database table.</p>
 */
@Entity
@Table(name = "products")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Product {

    /**
     * Surrogate primary key, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Display name of the product. Must not be {@code null}.
     */
    @Column(nullable = false)
    private String name;

    /**
     * Optional marketing / technical description of the product.
     * Stored as a VARCHAR with a maximum length of 2 000 characters.
     */
    @Column(length = 2000)
    private String description;

    /**
     * Current retail price of the product.
     * Stored with 12 integer digits and 2 decimal places (monetary precision).
     * Must not be {@code null}.
     */
    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal price;

    /**
     * Number of units currently available in stock.
     * Decremented at order placement; cannot go below zero.
     * Must not be {@code null}.
     */
    @Column(name = "stock_quantity", nullable = false)
    private Integer stockQuantity;

    /**
     * The categories this product belongs to.
     * Ownership of the join table ({@code product_category}) sits on this side.
     */
    @ManyToMany
    @JoinTable(
            name = "product_category",
            joinColumns = @JoinColumn(name = "product_id"),
            inverseJoinColumns = @JoinColumn(name = "category_id")
    )
    @Builder.Default
    private Set<Category> categories;
}
