package com.ejada.practice.entity;

import jakarta.persistence.*;
import lombok.*;

import java.util.HashSet;
import java.util.Set;

/**
 * JPA entity representing an application role (e.g. {@code USER}, {@code ADMIN}).
 *
 * <p>Roles are granted to {@link User}s via a many-to-many relationship stored
 * in the {@code user_roles} join table (owned by the {@link User} side).
 * Spring Security checks these roles as {@code ROLE_<name>} granted authorities.</p>
 *
 * <p>Mapped to the {@code roles} database table.</p>
 */
@Entity
@Table(name = "roles")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Role {

    /**
     * Surrogate primary key, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique role name stored in the database (e.g. {@code "USER"}, {@code "ADMIN"}).
     * Spring Security will prefix this with {@code "ROLE_"} when checking authorities.
     * Must not be {@code null}; maximum length is 30 characters.
     */
    @Column(nullable = false, unique = true, length = 30)
    private String name;

    /**
     * The users that have been assigned this role.
     * Mapped by the {@code roles} field on the {@link User} side.
     */
    @ManyToMany(mappedBy = "roles")
    private Set<User> users;
}
