package com.ejada.practice.entity;

import jakarta.persistence.*;
import lombok.*;


import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * JPA entity representing an application user.
 *
 * <p>A user can hold multiple {@link Role}s (many-to-many via the
 * {@code user_roles} join table) and may have placed several {@link Order}s
 * (one-to-many).  Account locking and enabling flags are consumed directly
 * by {@link com.ejada.practice.security.CustomUserDetails} to satisfy the
 * Spring Security {@code UserDetails} contract.</p>
 *
 * <p>Email changes go through a two-step verification flow: the new address
 * is stored in {@link #pendingEmail} together with a time-limited
 * {@link #emailVerificationToken}; the live {@link #email} is only updated
 * after the token is confirmed via {@code GET /api/users/verify-email}.</p>
 *
 * <p>Mapped to the {@code users} database table.</p>
 */
@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    /**
     * Surrogate primary key, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique login handle for the user.
     * Must not be {@code null}; maximum length is 50 characters.
     */
    @Column(nullable = false, unique = true, length = 50)
    private String username;

    /**
     * BCrypt-encoded password hash.  Never stored or exposed in plain text.
     * Must not be {@code null}.
     */
    @Column(nullable = false)
    private String password;

    /**
     * Verified e-mail address of the user (the address actively in use).
     * Must be unique across all accounts.
     * Must not be {@code null}.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * Given (first) name of the user.
     * Must not be {@code null}.
     */
    @Column(name = "first_name", nullable = false)
    private String firstName;

    /**
     * Family (last) name of the user.
     * Must not be {@code null}.
     */
    @Column(name = "last_name", nullable = false)
    private String lastName;

    /**
     * Whether the account is active.
     * Defaults to {@code true}; set to {@code false} to soft-disable the account.
     */
    @Column(nullable = false)
    private boolean enabled = true;

    /**
     * Whether the account is NOT locked.
     * Defaults to {@code true}; set to {@code false} after too many failed logins.
     *
     * @see com.ejada.practice.security.LoginAttemptService
     */
    @Column(name = "account_non_locked", nullable = false)
    private boolean accountNonLocked = true;

    /**
     * New e-mail address awaiting verification.
     * {@code null} when no email change is in progress.
     */
    @Column(name = "pending_email")
    private String pendingEmail;

    /**
     * One-time token sent to {@link #pendingEmail} to confirm the address.
     * {@code null} when no email change is in progress.
     */
    @Column(name = "email_verification_token")
    private String emailVerificationToken;

    /**
     * Timestamp after which {@link #emailVerificationToken} is no longer valid.
     * {@code null} when no email change is in progress.
     */
    @Column(name = "email_verification_expiry")
    private java.time.LocalDateTime emailVerificationExpiry;

    /**
     * The roles assigned to this user (e.g. {@code USER}, {@code ADMIN}).
     * Ownership of the {@code user_roles} join table sits on this side.
     */
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(
            name = "user_roles",
            joinColumns = @JoinColumn(name = "user_id"),
            inverseJoinColumns = @JoinColumn(name = "role_id")
    )
    private Set<Role> roles;

    /**
     * All orders placed by this user.
     */
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = false)
    private List<Order> orders;
}
